spring:
  datasource:
    url: jdbc:mysql://localhost:3308/edushareqa?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

logging:
  level:
    root: INFO
    com.edushareqa: DEBUG

