spring:
  datasource:
    url: jdbc:mysql://118.89.81.131:3306/edushareqa?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: clouduser
    password: 123456

logging:
  level:
    root: INFO
    com.edushareqa: DEBUG

